version: '3.5'

services:
  frontend:
    build: frontend
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    build: backend
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ewallet

  postgres:
    image: 'postgres:11.5-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ewallet
      POSTGRES_USER: ewallet
      POSTGRES_PASSWORD: ewallet
