spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewallet
    username: ewallet
    password: ewallet

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
server:
  servlet:
    context-path: /api
